### ISSUE TITLE
Server error, again

### ISSUE THREAD

**Issue by ElezeoraDraconius** [mukul500/AnimeXStream#290] opened 2021-09-07 10:48 UTC
Not even uninstalling and installing it back again seems to fix this issue this time so😭

**Comment by noobie13** [comment] 2021-09-07 12:23
> Not even uninstalling and installing it back again seems to fix this issue this time so😭

Yeah same happening with me too

**Comment by noobie13** [comment] 2021-09-07 13:07
> So i tried uninstalling and installing it for the last time hoping for some miracle.. It finally worked😷

Are you using Version 3.0.6 ?

**Comment by ElezeoraDraconius** [comment] 2021-09-07 13:09
Yea version3. 0.6.

**Comment by noobie13** [comment] 2021-09-07 13:14
> Ok so it turns out some anime will play and some will display "server error "

Ahh crap. I tried reinstalling couple of times too. It didn't work 😭

**Comment by Aftabyasir9** [comment] 2021-09-07 13:31
We can't do anything but wait for the developer to fix it or rather it gets fixed on it's own

**Comment by noobie13** [comment] 2021-09-07 13:42
> We can't do anything but wait for the developer to fix it or rather it gets fixed on it's own

The developer has stopped working on the app most probably 😭

**Comment by Aftabyasir9** [comment] 2021-09-07 13:43
I have contacted him personally, let's wait for his reply, he has stopped working on updates, but he said that he will still fix the issues ✌️

**Comment by Drxco4** [comment] 2021-09-07 23:00
Same L

**Comment by ElezeoraDraconius** [comment] 2021-09-08 00:49
Hope this app get fixed.. This app is literally the best app ever

**Comment by jirali** [comment] 2021-09-09 10:07
What do you mean version 3.0.6? I only see version 0.2.4.

**Comment by mukul500** [comment] 2021-09-20 11:32
The issue is resolved now, [Download v0.2.5](https://github.com/mukul500/AnimeXStream/releases)

**Closed by mukul500** 2021-09-20 11:32 UTC
