### ISSUE TITLE
PLEASE FIX SERVER ERROR

### ISSUE THREAD

**Issue by Carnaken** [mukul500/AnimeXStream#302] opened 2021-09-12 02:45 UTC
This is app is my most favorite because it easy to use and not laggy unlike aniyomi hope you fix it as fast as u can.

**Comment by pokurt** [comment] 2021-09-14 23:30
it will be fixed. be patient: https://github.com/mukul500/AnimeXStream/pull/304

**Comment by stark-cpu** [comment] 2021-09-17 15:20
![Screenshot_2021-09-17-20-48-50-373_net xblacky animexstream](https://user-images.githubusercontent.com/90656285/133807688-6c94128f-b2fd-47ae-a9b7-dcc037271883.png)
Please sir how much time to fix this problem

**Comment by mukul500** [comment] 2021-09-20 11:29
The issue is resolved now, [Download v0.2.5](https://github.com/mukul500/AnimeXStream/releases)

**Closed by mukul500** 2021-09-20 11:29 UTC
